/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reader;

import com.pi4j.io.gpio.Pin;
import com.pi4j.io.gpio.RaspiPin;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author Sandro
 */
public class ReaderGUI extends javax.swing.JFrame {

    private static Pin[] PIN_TABLE = new Pin[]{null,null,RaspiPin.GPIO_08,null,RaspiPin.GPIO_09,null,RaspiPin.GPIO_07,
        RaspiPin.GPIO_15,null,RaspiPin.GPIO_16,RaspiPin.GPIO_00,RaspiPin.GPIO_01,RaspiPin.GPIO_02,null,RaspiPin.GPIO_03,RaspiPin.GPIO_04,
        null,RaspiPin.GPIO_05,RaspiPin.GPIO_12,null,RaspiPin.GPIO_13,RaspiPin.GPIO_06,RaspiPin.GPIO_14,RaspiPin.GPIO_10,
        null,RaspiPin.GPIO_11,null,null,RaspiPin.GPIO_21,null,RaspiPin.GPIO_22,RaspiPin.GPIO_26,RaspiPin.GPIO_23,null,RaspiPin.GPIO_24,
        RaspiPin.GPIO_27,RaspiPin.GPIO_25,RaspiPin.GPIO_28,null,RaspiPin.GPIO_29};
    
    private List<Pin> pins = new ArrayList<>();
    
    public ReaderGUI() {
        initComponents();
        initComponents2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        onOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(0, 2));
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        onOk.setText("OK");
        onOk.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                onOk(evt);
            }
        });
        jPanel2.add(onOk, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onOk(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onOk
    {//GEN-HEADEREND:event_onOk
        Pin syncPin = pins.get(0);
        pins.remove(0);
        Pin dataPins[] = pins.toArray(new Pin[pins.size()]);
        
        ReaderGUIold r = new ReaderGUIold(syncPin, dataPins);
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_onOk

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReaderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReaderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReaderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReaderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReaderGUI().setVisible(true);
            }
        });
    }

    public void initComponents2(){
        for(int i = 0; i<panels.length; i++){
            panels[i] = new JPanel();
            panels[i].setBorder(BorderFactory.createLineBorder(Color.black));
            panels[i].setToolTipText(i+1 + "");
            panels[i].addMouseListener(new MouseAdapter()
            {
                @Override
                public void mouseClicked(MouseEvent e)
                {
                    Object tempi = e.getSource();
                    JPanel panel = (JPanel)tempi;
                    panel.setBackground(Color.red);
                    System.out.println(panel.getToolTipText());
                    pins.add(PIN_TABLE[Integer.parseInt(panel.getToolTipText())-1]);
                    super.mouseClicked(e); //To change body of generated methods, choose Tools | Templates.
                    
                }
            });
            jPanel1.add(panels[i]);
            
        }
    }
    
    private JPanel panels[] = new JPanel[40];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton onOk;
    // End of variables declaration//GEN-END:variables
}
